# Generated by Django 5.1.2 on 2024-10-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='id',
        ),
        migrations.AlterField(
            model_name='role',
            name='position',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
